@startebnf
title EBNF - XML Lexer

(* special tokens definitions *)

EOF = ? end of the file = no more charecteres to process ? ;

EOF = "RegExp( /^(?:\n|\r\n|\n\r)/ )" (* `\\n` on POSIX and `\\r\\n` on Windows *) ;

(* Skip *)

EMPTY_SPACE = "RegExp( /^[ \t]/ )" ;

COMMENT = "RegExp( /^<!--[\s\S]*?-->/ )" ;

XML_STYLESHEET = "RegExp( /^<\?xml\-stylesheet[\s\S]*?\?>/ )" ;

DTD =  "RegExp( /^<!DOCTYPE[\s\S]*?>/ )" ;


(* symbols *)

OPEN_TAG = "<" ;

CLOSE_TAG = ">" ;

SLASH = "/" ;

EQUALS = "=" ;


(* xml tokens *)

XML_DECL_START = "<?xml" ;

SPECIAL_CLOSE = "?>" ;

STRING = ? regexp ? (* RegExp( /^("[^"]*")|('[^']*')/ ) - anything in between "" or '' *) ;

NAME = "RegExp( /^\w+:?[\w-]+/ )" ;

TEXT = "RegExp( /^[^<]+/ )" ;

RAW_TEXT = "RegExp( /^(?<raw>[\s\S]+)<\// )" ;

CDATA = "RegExp( /^<!\[CDATA\[(?<raw>[\s\S]*)?\]\]\s?>/ )" ;

@endebnf