@startebnf
title EBNF - Basic XML Parser


Document = [ Prolog ] , Element , EOF (* end of file *) ;

Prolog = XML_DECL_START (* <?xml *) , { Attributes } (* { version, encoding? } *) , SPECIAL_CLOSE (* ?> *) ;

Element = (
    "<" , NAME , { Attribute } , "/" , ">" |
    "<" , NAME , { Attribute } , ">" , Content , "<" , "/" , NAME , ">"
  ) 
  ;

Attribute = NAME , "=" , STRING ;

Content = { ( 
    TEXT |
    Element
  ) }-
  ;

@endebnf