@startebnf
title EBNF - Basic XML Parser


Document = [ Prolog ] , Element , EOF (* end of file *) ;

Prolog = XML_DECL_START (* <?xml *) , { Attributes } (* { version, encoding? } *) , SPECIAL_CLOSE (* ?> *) ;

Element = (
    OPEN_TAG (* < *) , NAME , { Attribute } , SLASH (* / *) , CLOSE_TAG (* > *) |
    OPEN_TAG (* < *) , NAME , { Attribute } , CLOSE_TAG (* > *) , Content , OPEN_TAG (* < *) , SLASH (* / *) , NAME , CLOSE_TAG (* > *)
  ) 
  ;

Attribute = NAME , EQUALS (* = *) , STRING ;

Content = { ( 
    TEXT |
    Element
  ) }-
  ;

@endebnf